#!/bin/bash
ID=${1:-'YOUR-EC2-ID'}
aws ec2 start-instances --instance-ids $ID
IPV4="$(aws ec2 describe-instances --instance-ids $ID --query 'Reservations[].Instances[].PublicDnsName' --output text)"
ssh -i "PATH/TO/EC2-KEY.pem" ec2-user@$IPV4 -oStrictHostKeyChecking=no
